apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  labels:
    app: go-meta-app-label
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-selector-app
  template:
    metadata:
      labels:
        app: go-selector-app
    spec:
      containers:
        - name: go-container
          image: go-hello-world
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: LoadBalancer
  selector:
    app: go-selector-app
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8080